### ISSUE TITLE
Add the function `inverted_index_of(document_list)->(dict)` to indexer classes

### ISSUE THREAD

**Issue by adam-prochazka** [adam-prochazka/search-engine#18]
As from the official project task. There should be a method called `inverted_index_of`. Right now, there is a function called `index_all` that takes a directory name and indexes, indexes all the books and persistently saves the indexes. It does not return anything.

Is it ok like this or do you want to refactor the classes?
@BongoloZakolo @carlillous @JoelClemente @carlos-esplaa

**Comment by adam-prochazka** [comment]
But that would be in the dictionary indexer only. It's a bit trickier with the database.

**Comment by carlillous** [comment]
we could only implement it in the dictionary indexer and we can justify it saying that due that the dictionary was so much faster, we didn't want to keep developing the another indexer.

**Comment by adam-prochazka** [comment]
Since the task1 is closed, I guess we don't need to update the python files anymore.
