### ISSUE TITLE
Create Project Structure With Interfaces

### ISSUE THREAD

**Issue by adam-prochazka** [adam-prochazka/search-engine#36]

**Comment by adam-prochazka** [comment]
As the only modules that are being called and used by other applications are the Datalake and Datamart, I will just try to create Interfaces for these two if you agree.

@BongoloZakolo @carlillous @JoelClemente  @carlos-esplaa

**Comment by BongoloZakolo** [comment]
Vale

**Comment by adam-prochazka** [comment]
Is that an email reply?

**Comment by adam-prochazka** [comment]
I am on the DataMart interface. @JoelClemente could you create the Interface for your DataLake?
